version: 0.2

phases:
  build:
    commands:
      - sam build --template-file services/votes/sam.yml --build-dir .aws-sam/build --debug
      - cd .aws-sam/build
  post_build:
    commands:
      - sam package --output-template-file ../../services/votes/sam.yml --s3-bucket $SAM_RESOURCES_BUCKET --debug
      
artifacts:
  type: zip
  files:
    - '**/*'